Query 2.1
select sum(LO_REVENUE), toYear(LO_ORDERDATE) d_year, P_BRAND from lineorder ANY INNER JOIN (SELECT P_BRAND, P_PARTKEY LO_PARTKEY FROM part WHERE P_CATEGORY = 'MFGR#12') USING (LO_PARTKEY)  WHERE LO_SUPPKEY IN (SELECT S_SUPPKEY FROM supplier WHERE S_REGION = 'AMERICA') group by d_year, P_BRAND order by d_year, P_BRAND;
